### ISSUE TITLE
Hood.ie won't start

### ISSUE THREAD

**Issue by marktyers** [hoodiehq/bugs#2]
## Description

Attempting to run hood.ie on a docker instance using Codio.com IDE. Installed couchdb. Steps as follows:

parts install couchdb                                                                                          
npm install -g hoodie-cli                                                                                      
hoodie new guestbook                                                                                           
cd guestbook/                                                                                                  
hoodie start

## Error Message

ERR! Error: Timed out waiting for CouchDB. These logs may help:                                                       
ERR!    /home/codio/workspace/guestbook/data/couch.stderr                                                             
ERR!    /home/codio/workspace/guestbook/data/couch.stdout                                                             
ERR!    /home/codio/workspace/guestbook/data/couch.log                                                                
ERR!     at Request._callback (/home/codio/workspace/guestbook/node_modules/hoodie-server/lib/couchdb/index.js:145:27)
ERR!     at self.callback (/home/codio/workspace/guestbook/node_modules/hoodie-server/node_modules/request/request.js:
372:22)                                                                                                               
ERR!     at Request.EventEmitter.emit (events.js:95:17)                                                               
ERR!     at Request.onRequestError (/home/codio/workspace/guestbook/node_modules/hoodie-server/node_modules/request/re
quest.js:970:8)                                                                                                       
ERR!     at ClientRequest.EventEmitter.emit (events.js:95:17)                                                         
ERR!     at Socket.socketErrorListener (http.js:1547:9)                                                               
ERR!     at Socket.EventEmitter.emit (events.js:95:17)                                                                
ERR!     at net.js:441:14                                                                                             
ERR!     at process._tickDomainCallback (node.js:459:13)

* Type: bug
* Component: server
* Impact: medium
* Severity: broken expected use
* Requirements:

**Comment by janl** [comment]
Sorry for the alte reply, can you share the CouchDB log files?
