### ISSUE TITLE
Login-error: emitter does not fire

### ISSUE THREAD

**Issue by kvdmolen** [hoodiehq/bugs#6]
## Description

When trying to login with WRONG password, the "error" event does not fire:

    this.hoodie.on('account:error:unauthenticated remote:error:unauthenticated', this.handleUserAuthenticationError.bind(this));

This is a copy form the default todo-app, and neither there does it fire

## Error Message

* Type: bug
* Component: hoodie.js
* Impact: many
* Severity: broken expected use
* Requirements: 

It is also quite unclear how the following works, since both will fire all the time (both on correct password and wrong password) please help?

    var magic = hoodie.account.signIn(user,pass);
    magic.fail(console.log("fail"));
    magic.done(console.log("done"));

**Comment by gr2m** [comment]
The `account:error:unauthenticated` is fired when you are already signed in, but your session ended. If you enter a wrong password, the promise of `hoodie.account.signIn` will reject with the according error.

```js
hoodie.account.signIn(user,pass)
.fail(function(error) {
  // handle error
})
```

**Comment by kvdmolen** [comment]
Thanks for the clarification, I expected a "fire" upon wrong password. 
`.fail()` works great now
