### ISSUE TITLE
testapp admin dash board does not take password

### ISSUE THREAD

**Issue by PDXIII** [hoodiehq/bugs#7]
## Description

I followed the steps in your tutorial and tried to enter the admin dashboard with the password I entered before in the terminal. The response was: Invalid password.

## Error Message

Invalid password

* Type: bug
* Component: server
* Impact: many
* Severity: confusing
* Requirements:

**Comment by gr2m** [comment]
This is a known issue, we hope to release the fix soon: https://github.com/hoodiehq/hoodie-server/pull/331

For the time being, follow the workaround as described here: https://github.com/hoodiehq/hoodie-cli/issues/157#issue-52599005

**Comment by PDXIII** [comment]
I filed that issue over that template service. Thats why I haven’t seen the other issue. Sorry for double filing.

**Comment by janl** [comment]
fixed!

**Comment by PDXIII** [comment]
Top!
