### ISSUE TITLE
Links to Hoodie Cheat Sheet are broken

### ISSUE THREAD

**Issue by brylie** [hoodiehq/bugs#8]
## Description

On the hood.ie website, there are links to the Hoodie Cheatsheet. On at least two pages, the links to the Cheatsheet are broken (both a link to Github and one to the PDF version on the hood.ie website). Also, one of the links may be misnamed, as the HTML version seems to link to a PDF.

## Error Message

404

* Type: documentation
* Component: 
* Impact: medium
* Severity: broken expected use
* Requirements:

**Comment by Charlotteis** [comment]
Hi @brylie! We are aware of the issue and have made an issue already here: https://github.com/hoodiehq/hood.ie/issues/192

Thanks for feeding this back to us, we're working on it

☀️
